### ISSUE TITLE
Non linear load to energy consumption behavior

### ISSUE THREAD

**Issue by Tyrrx** [cloud-carbon-footprint/cloud-carbon-coefficients#31]
Hi, I just checked the SPECpower_ssj2008 dataset and saw that they contain much more than just the min and max energy consumption. So I wonder if there is there a specific reason why you assume a linear load to energy consumption behavior. Wouldn't it be better to perform a approximation over all available load levels (10% steps)?

[full SPECpower_ssj2008 dataset](https://www.spec.org/cgi-bin/osgresults?conf=power_ssj2008;op=dump;format=csvdump)

[SPECpower_ssj2008 form](https://www.spec.org/cgi-bin/osgresults?conf=power_ssj2008;op=form)

**Comment by davidmytton** [comment]
Thanks for your question. You can find an explanation of the methodology at https://www.cloudcarbonfootprint.org/docs/methodology#compute

If you have further questions, I suggest you post them over in https://groups.google.com/g/cloud-carbon-footprint sp someone who worked on the original methodology will be able to respond.
