### ISSUE TITLE
How are oversubscription ratios accounted for?

### ISSUE THREAD

**Issue by mrchrisadams** [cloud-carbon-footprint/cloud-carbon-coefficients#34]
I'm asking this mainly as a sanity check.

As I understand it, it's fairly common in cloud computing to make more vCPUS available than are really available.

Do these coefficients try to account for it, or should it happen further 'downstream' in tooling that might be consuming the data this repo generates?

**Why I'm asking and some related papers**

This paper refers to the practice in more detail - [Simulating the Effects of Cloud-based Oversubscription On Datacenter Revenues and Performance in Single and Multi-class Service Levels](https://www.researchgate.net/publication/282975152_Simulating_the_Effects_of_Cloud-based_Oversubscription_On_Data_Center_Revenues_and_Performance_in_Single_and_Multi-class_Service_Levels)

There's a more recent paper here too, from 2019 - [Optimal Overbooking Policy for Cloud Service Providers: Profit and Service Quality](https://www.researchgate.net/publication/334286840_Optimal_Overbooking_Policy_for_Cloud_Service_Providers_Profit_and_Service_Quality)

There's also this paper here, explaining how in can be _increased_ from its current amount, by 2x - [Prediction-Based Power Oversubscription in Cloud Platforms](https://www.microsoft.com/en-us/research/publication/prediction-based-power-oversubscription-in-cloud-platforms/).

**Comment by mrchrisadams** [comment]
Just looking back at the original cloud jewels methodology. This makes me assume no oversubscription is accounted for, where a vCPU is roughly equivalent to a server thread.

https://github.com/etsy/cloud-jewels/blob/master/methodology.md#application-given-what-we-know-about-googles-infrastructure

This isn't my area of expertise, so I'd be happy to learn more.

**Comment by davidmytton** [comment]
It's based on the Cloud Jewels methodology using vCPU hours as reported by the billing data - there's no built-in assumptions around oversubscription. A full description is at https://www.cloudcarbonfootprint.org/docs/methodology#compute but you may find asking in https://groups.google.com/g/cloud-carbon-footprint helpful as well, since the full CCF team monitor that group.
